### PR TITLE
Add spelling suggestions to context menu

### PR DESCRIPTION
**Pull request by DUOLabs333**

### CODE REVIEW

**Comment by Alexey-T** [comment]
```
        ed.set_caret(info['x'], info['y'], info['x']+len(sub), info['y'])
        ed.delete(info['x'], info['y'], info['x']+len(sub), info['y'])
        ed.insert(info['x'], info['y'], word)
```
it is slow - N dict lookups. better use new variables - x, y

**Comment by DUOLabs333** [comment]
Dict lookups are not slow enough for this to be an issue (also aren't they supposed to be O(1)?)

**Comment by Alexey-T** [comment]
ok. will review more.

**Comment by Alexey-T** [comment]
```
        ed.delete(info['x'], info['y'], info['x']+len(sub), info['y'])
        ed.insert(info['x'], info['y'], word)
```
better ed.replace() ?

**Comment by DUOLabs333** [comment]
There doesn't seem to be documentation on it. I was just using the function from another part of the code.

**Comment by Alexey-T** [comment]
```
    if dict_obj.check(word):
        menu_proc(spelling,MENU_REMOVE)
        return
```

instead of remove item, can you pls add it always, and set its Visible to false?

**Comment by Alexey-T** [comment]
instead of doing MENU_REMOVE, can you pls only HIDE the item (set visible to False)?

**Comment by Alexey-T** [comment]
`   for _ in dict_obj.suggest(word):`

will conflict with I18N function name

**Comment by DUOLabs333** [comment]
> ` for _ in dict_obj.suggest(word):`
> 
> will conflict with I18N function name

What do you mean?

**Comment by DUOLabs333** [comment]
No, I did that on purpose --- I want to make it clear that it's still wrong, just nothing was found. This is how Sublime works as well.

**Comment by Alexey-T** [comment]
okay.
```
def get_current_word_under_caret():
    info=caret_info()
    return info['line'][info['n1']:info['n2']+1]

def replace_current_word_with_word(word):
    def temp():
        info=caret_info()
        ed.replace(info['x'], info['y'], info['x']+len(get_current_word_under_caret()), info['y'],word)
```

here you call caret_info 2 times! why no to reuse 1st call

**Comment by DUOLabs333** [comment]
I'm confused --- what do you mean?

**Comment by Alexey-T** [comment]
I posted the inline comment above- see `can it be this?`

**Comment by Alexey-T** [comment]
i mean this shorted code
```
    def temp():
        info=caret_info()
        nlen=info['n2']-info['n1']+1
        ed.replace(info['x'], info['y'], info['x']+nlen, info['y'],word)
```

**Comment by DUOLabs333** [comment]
Oh, hmmm... I wanted to separate the logic just in case it changed later on.

**Comment by DUOLabs333** [comment]
What comment? On the commits?

**Comment by Alexey-T** [comment]
it is on this webpage- search for `on_change_slow,on_click`

**Comment by DUOLabs333** [comment]
No, I don't see anything.

**Comment by DUOLabs333** [comment]
Where is it posted?

**Comment by Alexey-T** [comment]
okay, GH is weeird.

1) on_change_slow is subscribed DINAMICALLY, on purpose. don't set it in install.inf
```
    def config_events(self):
        filename_inf = os.path.join(_mydir, 'install.inf')
        v = ini_read(filename_inf, 'item1', 'events', '')
        b_open = ',on_open,' in ','+v+','
        b_change = ',on_change_slow,' in ','+v+','

        WARN1 = _('To not slow down CudaText when events are off, plugin saves these settings to install.inf file.')
        WARN2 = _('So you need to re-configure these options each time you update Spell Checker plugin.')
        WARN3 = _('Settings will take effect after CudaText restart.')

        DLG_W = 680  # 626 is too small for translations
        DLG_H = 180
        BTN_W = 80
        c1 = chr(1)

        res = dlg_custom(_('Configure events'), DLG_W, DLG_H, '\n'.join([]
              + [c1.join(['type=check', 'cap='+_('Handle event "on_open" (opening of a file)'), 'pos=6,6,400,0', 'val='+bool_to_str(b_open)])]
              + [c1.join(['type=check', 'cap='+_('Handle event "on_change_slow" (editing of file + pause)'), 'pos=6,36,400,0', 'val='+bool_to_str(b_change)])]
```

2) on_click - make it LAZY in install.inf pls. see the API wiki about 'lazy'

**Comment by Alexey-T** [comment]
```
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_spell_checker/__init__.py", line 431, in on_click
    context_menu()
  File "/home/user/.config/cudatext/py/cuda_spell_checker/__init__.py", line 87, in context_menu
    word=get_current_word_under_caret()
  File "/home/user/.config/cudatext/py/cuda_spell_checker/__init__.py", line 78, in get_current_word_under_caret
    return info['line'][info['n1']:info['n2']+1]
TypeError: 'NoneType' object is not subscriptable
ERROR: Exception in CudaText for on_click: TypeError: 'NoneType' object is not subscriptable
```

**Comment by DUOLabs333** [comment]
This probably happens only when there's no word --- in this case, it doesn't matter what happens and the error can be ignored.

**Comment by Alexey-T** [comment]
sorry no, the console errors must always be fixed. i clicked on empty line.

**Comment by Alexey-T** [comment]
okay.
now I see that plugin don't always shows suggestions in menu! e.g. I opened file
```
test 
teeet teet

tesetwtttsetttttttttt

```
and then I put caret on last word and type n chars. no spell checking + no underlines

**Comment by DUOLabs333** [comment]
I see an underline, but what do you mean by "No suggestions"? If it's "(No suggestions found)", then it's because there are no suggestions to give.

**Comment by Alexey-T** [comment]
video,
[Kazam_00000.zip](https://github.com/CudaText-addons/cuda_spell_checker/files/9470604/Kazam_00000.zip)

**Comment by DUOLabs333** [comment]
Huh, it works fine for me.

**Comment by Alexey-T** [comment]
- it don't work for file 'new' but works if filename is 'new.txt'. why?
- glitch in your code. open a file. put caret into a BAD word. type few chars --> spell checked, but right-click don't show 'spelling'

**Comment by Alexey-T** [comment]
found why. config option did not let files with '-' lexer to check.

**Comment by Alexey-T** [comment]
video2 of that glitch

[Kazam_00001.zip](https://github.com/CudaText-addons/cuda_spell_checker/files/9470990/Kazam_00001.zip)

**Comment by DUOLabs333** [comment]
It still works for me, can you try a clean profile?

**Comment by Alexey-T** [comment]
after
```
    if dict_obj.check(word):
        menu_proc(spelling,MENU_SET_VISIBLE,command=False)
        return
```
you miss SHOWING the item again, when words found next time

**Comment by Alexey-T** [comment]
2. please use empty lines as separator between new `def`s.

**Comment by Alexey-T** [comment]
fix is
```
    
    ok = dict_obj.check(word)
    menu_proc(spelling,MENU_SET_VISIBLE,command=not ok)
    if ok:
        return
```

**Comment by Alexey-T** [comment]
4. add to history.txt this
```
2022.09.01
+ add: when you click a misspelled word, plugin modifies the editor context menu, it ass there "Spelling" sub-menu with suggestions (patch by @DUOLabs333)
```

**Review by Alexey-T — APPROVED** [review]

**Comment by DUOLabs333** [comment]
Just a note: for some reason, `on_change_slow~` makes the underlines not show up.

**Comment by CudaText-addons** [comment]
after "Spell check" command I see underlines.
what are steps to not see them?

**Comment by DUOLabs333** [comment]
Oh, you have to first activate it with the command.

**Comment by Alexey-T** [comment]
yes, otherwise 'lazy' event dont work.

**Pull request merged**
