### PR TITLE
Add support for 64 bit Windows

### PR DESCRIPTION
**Pull request by dinkumoil**
I have doubled the _Enchant_ directory, one for 32 bit and one for 64 bit version. By using Python _importlib_ I was able to dynamically import the correct python packages at runtime.

For future changes, the maintainer will need to update 2 sets of Python code. However, since the files are 100% identical, this can be done with differ tool.

### CODE REVIEW

**Comment by Alexey-T** [comment]
I want to make single python code, with two dirs of dll files, I will try it soon. Enchant lib needs a change in the place where it imports dlls

**Comment by dinkumoil** [comment]
_Enchant_'s Dll loading code is only one part of the problem. The second part is loading the dictionaries.

The only way you can change that is recompiling _Enchant_ (the old outdated sources). This way you can create 64 bit DLLs anyway and all my work is for nothing. :-(

**Comment by dinkumoil** [comment]
So, if you decide to go the recompile way please close this pull request. Then I will delete my fork of the plugin.

**Comment by Alexey-T** [comment]
Okay, I will apply this patch. A hint- os.path.join allows any count of parameters, no need to call it 3 times per line

**Comment by dinkumoil** [comment]
Thank you.

As you know, I'm a Python beginner. I don't know the very details of every library call. Since editing of this PR for maintainers is allowed feel free to improve the code.

**Pull request merged**
