### PR TITLE
Update Enchant to v2.2.7

### PR DESCRIPTION
**Pull request by dinkumoil**
Fixes Alexey-T/CudaText#4623

### CODE REVIEW

**Comment by dinkumoil** [comment]
Please note: 32 bit version is untested!

**Comment by veksha** [comment]
> 32 bit version is untested but **should** work

it works too. nice job.

**Comment by veksha** [comment]
I think some of last changes by Alexey is not included in your commit, @dinkumoil.
incorrect rebasing?

for example, i can't turn `on_open` event off. Spell Checker is always on.

**Comment by dinkumoil** [comment]
@veksha 

> > 32 bit version is untested but **should** work
> 
> it works too.

Thank you for testing!

> I think some of last changes by Alexey is not included in your commit

Not possible, I created my fork yesterday from most recent state of plugin repo. This is a screenshot of _GitHub_'s _Network_ view of the repo:

grafik

>  i can't turn on_open event off. Spell Checker is always on.

Can not confirm, I'm able to turn it off and on using _Configure events_ dialog. Configuring both kinds of events works as it should.

**Comment by Alexey-T** [comment]
@dinkumoil 
somehow you got the old version, which don't have my last update in GH:

sd

these commits missed by you:

se

**Comment by dinkumoil** [comment]
Maybe this is caused by my poor knowledge of _Git_ and working with _GitHub_ forks and branches. Please close this PR, I will create a new fork and try to start from scratch. If you have another idea how to proceed please let me know.

**Comment by Alexey-T** [comment]
if 'from scracth' then maybe you can use 2.3.3 ?

**Comment by dinkumoil** [comment]
No, I will use the _Enchant_ files from this PR. Additionally to v2.3.3 _Enchant_ files maybe I would have to grab new versions of the 3rd party DLL files used by enchant as well. Too time consuming.

**Comment by veksha** [comment]
> Maybe this is caused by my poor knowledge of _Git_ and working with _GitHub_ forks and branches. Please close this PR, I will create a new fork and try to start from scratch. If you have another idea how to proceed please let me know.

maybe you can use "interactive rebase" and "drop" four Alexey's commits and then rebase against "master" to get them back. (solving conflicts along the way). I tried that locally and it worked, I think.
but I see you have already solved this problem and pushed changes, so nevermind.

**Pull request closed without merging**
